/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

synchronized public void win_draw1(PApplet appc, GWinData data) { //_CODE_:window1:446918:
  appc.background(230);
} //_CODE_:window1:446918:

public void EconomySlider(GSlider source, GEvent event) { //_CODE_:EconomyPercentage:449927:
  if(economyPercent != EconomyPercentage.getValueI()){
    economyPercent = EconomyPercentage.getValueI();
    BusinessPercentage.setValue(100-EconomyPercentage.getValueI());
    
  }
  
} //_CODE_:EconomyPercentage:449927:

public void BusinessSlider(GSlider source, GEvent event) { //_CODE_:BusinessPercentage:650300:
  if(businessPercent != BusinessPercentage.getValueI()){
    businessPercent = BusinessPercentage.getValueI();
    EconomyPercentage.setValue(100-BusinessPercentage.getValueI());
    
  }

} //_CODE_:BusinessPercentage:650300:

public void EconomySideDropFUNC(GDropList source, GEvent event) { //_CODE_:EconomySideDrop:873899:
  economySidesWidth = int(EconomySideDrop.getSelectedText());
  
} //_CODE_:EconomySideDrop:873899:

public void EconomyMidDropFUNC(GDropList source, GEvent event) { //_CODE_:EconomyMidDrop:877961:
  economyMiddleWidth = int(EconomyMidDrop.getSelectedText());
  
} //_CODE_:EconomyMidDrop:877961:

public void BusinessMidDropfunc(GDropList source, GEvent event) { //_CODE_:BusinessMidDrop:668383:
  businessSidesWidth = int(BusinessSideDrop.getSelectedText());
  
} //_CODE_:BusinessMidDrop:668383:

public void BusinessSideDropfnc(GDropList source, GEvent event) { //_CODE_:BusinessSideDrop:965563:
  businessMiddleWidth = int(BusinessMidDrop.getSelectedText());
  
} //_CODE_:BusinessSideDrop:965563:

public void PlaneSizeSliderfunc(GSlider source, GEvent event) { //_CODE_:PlaneSizeSlider:732488:
  planeSize = PlaneSizeSlider.getValueI();
  
} //_CODE_:PlaneSizeSlider:732488:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  window1 = GWindow.getWindow(this, "Window title", 0, 0, 400, 400, JAVA2D);
  window1.noLoop();
  window1.setActionOnClose(G4P.KEEP_OPEN);
  window1.addDrawHandler(this, "win_draw1");
  togGroup1 = new GToggleGroup();
  EconomyPercentage = new GSlider(window1, 30, 60, 162, 61, 10.0);
  EconomyPercentage.setShowValue(true);
  EconomyPercentage.setLimits(50, 0, 100);
  EconomyPercentage.setNbrTicks(5);
  EconomyPercentage.setShowTicks(true);
  EconomyPercentage.setNumberFormat(G4P.INTEGER, 0);
  EconomyPercentage.setOpaque(false);
  EconomyPercentage.addEventHandler(this, "EconomySlider");
  BusinessPercentage = new GSlider(window1, 207, 58, 163, 61, 10.0);
  BusinessPercentage.setShowValue(true);
  BusinessPercentage.setShowLimits(true);
  BusinessPercentage.setLimits(50, 0, 100);
  BusinessPercentage.setNbrTicks(5);
  BusinessPercentage.setShowTicks(true);
  BusinessPercentage.setNumberFormat(G4P.INTEGER, 0);
  BusinessPercentage.setOpaque(false);
  BusinessPercentage.addEventHandler(this, "BusinessSlider");
  EconomySideDrop = new GDropList(window1, 21, 167, 83, 92, 3, 10);
  EconomySideDrop.setItems(loadStrings("list_873899"), 0);
  EconomySideDrop.addEventHandler(this, "EconomySideDropFUNC");
  EconomyMidDrop = new GDropList(window1, 112, 167, 83, 92, 3, 10);
  EconomyMidDrop.setItems(loadStrings("list_877961"), 0);
  EconomyMidDrop.addEventHandler(this, "EconomyMidDropFUNC");
  BusinessMidDrop = new GDropList(window1, 297, 167, 83, 92, 3, 10);
  BusinessMidDrop.setItems(loadStrings("list_668383"), 0);
  BusinessMidDrop.addEventHandler(this, "BusinessMidDropfunc");
  BusinessSideDrop = new GDropList(window1, 204, 167, 83, 92, 3, 10);
  BusinessSideDrop.setItems(loadStrings("list_965563"), 0);
  BusinessSideDrop.addEventHandler(this, "BusinessSideDropfnc");
  EconomypercentTEXT = new GLabel(window1, 30, 34, 163, 20);
  EconomypercentTEXT.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  EconomypercentTEXT.setText("Economy Percentage");
  EconomypercentTEXT.setOpaque(false);
  BusinesspercentTEXT = new GLabel(window1, 207, 33, 163, 20);
  BusinesspercentTEXT.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  BusinesspercentTEXT.setText("Business Percentage");
  BusinesspercentTEXT.setOpaque(false);
  EconomySideDropTEXT = new GLabel(window1, 21, 137, 80, 26);
  EconomySideDropTEXT.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  EconomySideDropTEXT.setText("Economy Side");
  EconomySideDropTEXT.setOpaque(false);
  EconomyMidDropTEXT = new GLabel(window1, 114, 137, 73, 26);
  EconomyMidDropTEXT.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  EconomyMidDropTEXT.setText("Economy Mid");
  EconomyMidDropTEXT.setOpaque(false);
  BusinessSideDropTEXT = new GLabel(window1, 204, 136, 80, 28);
  BusinessSideDropTEXT.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  BusinessSideDropTEXT.setText("Business Side");
  BusinessSideDropTEXT.setOpaque(false);
  BusinessMidDropTEXT = new GLabel(window1, 300, 136, 74, 28);
  BusinessMidDropTEXT.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  BusinessMidDropTEXT.setText("Business Mid");
  BusinessMidDropTEXT.setOpaque(false);
  PlaneSizeSlider = new GSlider(window1, 19, 299, 362, 52, 10.0);
  PlaneSizeSlider.setShowValue(true);
  PlaneSizeSlider.setShowLimits(true);
  PlaneSizeSlider.setLimits(35, 20, 50);
  PlaneSizeSlider.setNbrTicks(31);
  PlaneSizeSlider.setStickToTicks(true);
  PlaneSizeSlider.setNumberFormat(G4P.INTEGER, 0);
  PlaneSizeSlider.setOpaque(false);
  PlaneSizeSlider.addEventHandler(this, "PlaneSizeSliderfunc");
  PlaneSizeText = new GLabel(window1, 19, 272, 363, 20);
  PlaneSizeText.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  PlaneSizeText.setText("Plane Size (m)");
  PlaneSizeText.setOpaque(false);
  window1.loop();
}

// Variable declarations 
// autogenerated do not edit
GLabel EconomypercentTEXT; 
GLabel BusinesspercentTEXT; 
GLabel EconomySideDropTEXT; 
GLabel EconomyMidDropTEXT; 
GLabel BusinessSideDropTEXT; 
GLabel BusinessMidDropTEXT; 

GWindow window1;

GToggleGroup togGroup1; 
GSlider EconomyPercentage; 
GSlider BusinessPercentage; 
GDropList EconomySideDrop; 
GDropList EconomyMidDrop; 
GDropList BusinessMidDrop; 
GDropList BusinessSideDrop; 
GSlider PlaneSizeSlider; 
GLabel PlaneSizeText; 
